// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint.proto
// Protobuf C++ Version: 6.32.0

#ifndef joint_2eproto_2epb_2eh
#define joint_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_joint_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_joint_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_joint_2eproto;
}  // extern "C"
class JointCommand;
struct JointCommandDefaultTypeInternal;
extern JointCommandDefaultTypeInternal _JointCommand_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull JointCommand_class_data_;
class JointState;
struct JointStateDefaultTypeInternal;
extern JointStateDefaultTypeInternal _JointState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull JointState_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class JointState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:JointState) */ {
 public:
  inline JointState() : JointState(nullptr) {}
  ~JointState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JointState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JointState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointState(::google::protobuf::internal::ConstantInitialized);

  inline JointState(const JointState& from) : JointState(nullptr, from) {}
  inline JointState(JointState&& from) noexcept
      : JointState(nullptr, ::std::move(from)) {}
  inline JointState& operator=(const JointState& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointState& operator=(JointState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointState& default_instance() {
    return *reinterpret_cast<const JointState*>(
        &_JointState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JointState& a, JointState& b) { a.Swap(&b); }
  inline void Swap(JointState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JointState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JointState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JointState& from) { JointState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JointState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "JointState"; }

 protected:
  explicit JointState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JointState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JointState& from);
  JointState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JointState&& from) noexcept
      : JointState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kEffortFieldNumber = 4,
    kTimestampFieldNumber = 1,
  };
  // repeated float position = 2;
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // repeated float velocity = 3;
  int velocity_size() const;
  private:
  int _internal_velocity_size() const;

  public:
  void clear_velocity() ;
  float velocity(int index) const;
  void set_velocity(int index, float value);
  void add_velocity(float value);
  const ::google::protobuf::RepeatedField<float>& velocity() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_velocity();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_velocity() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_velocity();

  public:
  // repeated float effort = 4;
  int effort_size() const;
  private:
  int _internal_effort_size() const;

  public:
  void clear_effort() ;
  float effort(int index) const;
  void set_effort(int index, float value);
  void add_effort(float value);
  const ::google::protobuf::RepeatedField<float>& effort() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_effort();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_effort() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_effort();

  public:
  // double timestamp = 1;
  void clear_timestamp() ;
  double timestamp() const;
  void set_timestamp(double value);

  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);

  public:
  // @@protoc_insertion_point(class_scope:JointState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JointState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::RepeatedField<float> velocity_;
    ::google::protobuf::RepeatedField<float> effort_;
    double timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull JointState_class_data_;
// -------------------------------------------------------------------

class JointCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:JointCommand) */ {
 public:
  inline JointCommand() : JointCommand(nullptr) {}
  ~JointCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JointCommand* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JointCommand));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointCommand(::google::protobuf::internal::ConstantInitialized);

  inline JointCommand(const JointCommand& from) : JointCommand(nullptr, from) {}
  inline JointCommand(JointCommand&& from) noexcept
      : JointCommand(nullptr, ::std::move(from)) {}
  inline JointCommand& operator=(const JointCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointCommand& operator=(JointCommand&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JointCommand& default_instance() {
    return *reinterpret_cast<const JointCommand*>(
        &_JointCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(JointCommand& a, JointCommand& b) { a.Swap(&b); }
  inline void Swap(JointCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointCommand* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JointCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JointCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JointCommand& from) { JointCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JointCommand* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "JointCommand"; }

 protected:
  explicit JointCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JointCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JointCommand& from);
  JointCommand(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JointCommand&& from) noexcept
      : JointCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kTimestampFieldNumber = 1,
  };
  // repeated float position = 2;
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // repeated float velocity = 3;
  int velocity_size() const;
  private:
  int _internal_velocity_size() const;

  public:
  void clear_velocity() ;
  float velocity(int index) const;
  void set_velocity(int index, float value);
  void add_velocity(float value);
  const ::google::protobuf::RepeatedField<float>& velocity() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_velocity();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_velocity() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_velocity();

  public:
  // double timestamp = 1;
  void clear_timestamp() ;
  double timestamp() const;
  void set_timestamp(double value);

  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);

  public:
  // @@protoc_insertion_point(class_scope:JointCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JointCommand& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::RepeatedField<float> velocity_;
    double timestamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_joint_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull JointCommand_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JointState

// double timestamp = 1;
inline void JointState::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double JointState::timestamp() const {
  // @@protoc_insertion_point(field_get:JointState.timestamp)
  return _internal_timestamp();
}
inline void JointState::set_timestamp(double value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:JointState.timestamp)
}
inline double JointState::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void JointState::_internal_set_timestamp(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// repeated float position = 2;
inline int JointState::_internal_position_size() const {
  return _internal_position().size();
}
inline int JointState::position_size() const {
  return _internal_position_size();
}
inline void JointState::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline float JointState::position(int index) const {
  // @@protoc_insertion_point(field_get:JointState.position)
  return _internal_position().Get(index);
}
inline void JointState::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.position)
}
inline void JointState::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:JointState.position)
}
inline const ::google::protobuf::RepeatedField<float>& JointState::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointState.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL JointState::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointState.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
JointState::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
JointState::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated float velocity = 3;
inline int JointState::_internal_velocity_size() const {
  return _internal_velocity().size();
}
inline int JointState::velocity_size() const {
  return _internal_velocity_size();
}
inline void JointState::clear_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_.Clear();
}
inline float JointState::velocity(int index) const {
  // @@protoc_insertion_point(field_get:JointState.velocity)
  return _internal_velocity().Get(index);
}
inline void JointState::set_velocity(int index, float value) {
  _internal_mutable_velocity()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.velocity)
}
inline void JointState::add_velocity(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_velocity()->Add(value);
  // @@protoc_insertion_point(field_add:JointState.velocity)
}
inline const ::google::protobuf::RepeatedField<float>& JointState::velocity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointState.velocity)
  return _internal_velocity();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL JointState::mutable_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointState.velocity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_velocity();
}
inline const ::google::protobuf::RepeatedField<float>&
JointState::_internal_velocity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
JointState::_internal_mutable_velocity() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.velocity_;
}

// repeated float effort = 4;
inline int JointState::_internal_effort_size() const {
  return _internal_effort().size();
}
inline int JointState::effort_size() const {
  return _internal_effort_size();
}
inline void JointState::clear_effort() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.effort_.Clear();
}
inline float JointState::effort(int index) const {
  // @@protoc_insertion_point(field_get:JointState.effort)
  return _internal_effort().Get(index);
}
inline void JointState::set_effort(int index, float value) {
  _internal_mutable_effort()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointState.effort)
}
inline void JointState::add_effort(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_effort()->Add(value);
  // @@protoc_insertion_point(field_add:JointState.effort)
}
inline const ::google::protobuf::RepeatedField<float>& JointState::effort() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointState.effort)
  return _internal_effort();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL JointState::mutable_effort()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointState.effort)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_effort();
}
inline const ::google::protobuf::RepeatedField<float>&
JointState::_internal_effort() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.effort_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
JointState::_internal_mutable_effort() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.effort_;
}

// -------------------------------------------------------------------

// JointCommand

// double timestamp = 1;
inline void JointCommand::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline double JointCommand::timestamp() const {
  // @@protoc_insertion_point(field_get:JointCommand.timestamp)
  return _internal_timestamp();
}
inline void JointCommand::set_timestamp(double value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:JointCommand.timestamp)
}
inline double JointCommand::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void JointCommand::_internal_set_timestamp(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// repeated float position = 2;
inline int JointCommand::_internal_position_size() const {
  return _internal_position().size();
}
inline int JointCommand::position_size() const {
  return _internal_position_size();
}
inline void JointCommand::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
}
inline float JointCommand::position(int index) const {
  // @@protoc_insertion_point(field_get:JointCommand.position)
  return _internal_position().Get(index);
}
inline void JointCommand::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointCommand.position)
}
inline void JointCommand::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  // @@protoc_insertion_point(field_add:JointCommand.position)
}
inline const ::google::protobuf::RepeatedField<float>& JointCommand::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointCommand.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL JointCommand::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointCommand.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
JointCommand::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
JointCommand::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// repeated float velocity = 3;
inline int JointCommand::_internal_velocity_size() const {
  return _internal_velocity().size();
}
inline int JointCommand::velocity_size() const {
  return _internal_velocity_size();
}
inline void JointCommand::clear_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.velocity_.Clear();
}
inline float JointCommand::velocity(int index) const {
  // @@protoc_insertion_point(field_get:JointCommand.velocity)
  return _internal_velocity().Get(index);
}
inline void JointCommand::set_velocity(int index, float value) {
  _internal_mutable_velocity()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointCommand.velocity)
}
inline void JointCommand::add_velocity(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_velocity()->Add(value);
  // @@protoc_insertion_point(field_add:JointCommand.velocity)
}
inline const ::google::protobuf::RepeatedField<float>& JointCommand::velocity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointCommand.velocity)
  return _internal_velocity();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL JointCommand::mutable_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointCommand.velocity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_velocity();
}
inline const ::google::protobuf::RepeatedField<float>&
JointCommand::_internal_velocity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.velocity_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
JointCommand::_internal_mutable_velocity() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.velocity_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // joint_2eproto_2epb_2eh
